export const FIELD = {
    No_Order: '您还无订单哦',
    No_Shopping: '您还没有购买商品哦',
    No_EvaluationL: '您还没有评价哦',
    No_Comment: '居然没人评论',
    Not_Found: '很抱歉，没有搜到该商品',
    No_Template: '暂无模板',
    No_Commodity: '暂无商品',
    No_Collection: '您还没有收藏哦',
    No_News: '暂无消息',
    No_Customer: '暂无客户',
    No_Evaluation: '暂无历史',
    No_Business: '暂无业务',
    No_Goods: '啥玩意也没有啊。',
    Await: '您的开店申请已提交，审核结果在3个工作日内公布，您可登陆网站WWW.XXX.COM查看相关信息。',
    Audit_Failure: '您填写的信息有误，请前往填写后再次提交审核。',
    Succeed: '',
    Page_Crash: '当前页面已崩溃，请返回前一页',
    Net_Error: '网络异常，请稍后再试',
    Server_Error: '服务器异常，请稍后再试'
};
