/**
 * 用于界面消息显示，错误提示等
 */
export const MESSAGE = {
    Network_Error: '网络异常，请稍后再试',
    Network_Cancel: '请求终止',
    No_Url: '请求地址不存在',

    LOGIN: {
        // PASS_ERR: '输入的账号和密码不匹配',

        //核查确定有用
        SET_YOUR_CODE: '请输入验证码',
        PLACEHOLDER: '请输入手机号或UID',
        LODE_BY_CODE: '验证码登陆',
        LODE_BY_PASSWORD: '密码登陆',
        GET_CODE: '获取验证码',
        SEND_AGAIN: '重新发送',
        SET_YOUR_PASSWORD: '请输入密码',
        FORGOT_PASSWORD: '忘记密码',
        GET_ANY: '没有收到验证码',
        PLACEHOLDER_DEFAULT: '请输入手机号'
    },

    Form: {
        ShopName_Err: '店铺名称由2-30位字符组成',
        No_Captcha: '请输入验证码',
        No_Content: '您还没有输入任何内容',
        No_Data: '您还没有选择任何数据',
        No_IssueDescribe: '请添加您的问题描述',
        No_IssueType: '请选择问题类型',
        No_Name: '请输入名字，且需为2~8位的中文字符',
        // No_NickName: '请输入昵称，且需为2~20位的字符',
        No_NickName: '请输入昵称',
        No_Phone: '请输入电话号码',
        No_Password: '请输入密码',
        No_Account: '请选择账号',
        // No_Purchase: '购买商品数量不能为0',（商品最低为1）
        No_Repeat: '不能重复添加商品',
        No_Search_Address: '请输入你想搜索的地址',
        No_Search_Shop: '没有搜索到这家店',
        No_PayMoney: '请选择付款方式',
        // No_userName: '请输入开店人姓名，且需为2~8位的中文字符',
        No_idCard: '请填写身份证号',
        // LongerShopName: '请输入店铺名称，且需为2~8字符',
        No_correctInfo: '请填写正确信息',
        // No_bankCard: '请输入正确的银行卡号',
        // No_openTime: '请设置营业时间',
        No_closeTime: '请选择打烊时间',
        No_deleAllCollect: '是否清空所有收藏?',
        No_delete: '是否删除?',
        No_lgPhone: '暂无物流电话',
        No_Click: '抱歉，需要在自动确认收货三天内才可申请成功',
        No_Error_Take: '确认收货前，请仔细核对商品。确保商品无误。是否确认收货。',
        No_Error_Has_Return: '该订单中存在有退款记录的商品,确认收货将撤销退款申请。',
        No_Difference: '请输入与本人身份证一致的银行卡号，仅支持借记卡',
        No_Merchant: '您不是商家，没有业务收入，是否前往申请开店',
        You_Extension_Agent: '您是推广员，没有业务收入',
        Switching_Businessmen: '请切换成商家的身份，再进行查看',
        // No_Payment_Code: '您还未设置支付密码，暂不能使用CAM余额消费。',
        // No_Chance: '您的密码输入错误机会已上限！今天无法再进行支付！请明天再试试！',
        No_Select_Select: '请选择要操作的对象',
        // No_Check: '您还没有勾选线下消费协议',
        // No_Less: '该商品不能再少了',
        // No_Mode_Specification: '请选择配送方式或商品规格',
        //No_qualification: '您还没有开店资格，暂不能开店，快去确认推荐人吧',
        // Whether_Empty: '您是否确定清空购物车内所有商品',
        // Whether_Delete_Commodity: '您是否确认将这个商品删除',
        Whether_Empty_Favorite: '是否清空所有收藏？',
        Whether_Revocation_Apply: '是否确认撤销申请',

        Error_Address_Required: '请输入详细地址',
        Error_Evaluate_Length: '评论内容不可以超过50个字',
        Error_EvaluateSelf: '不能评论自己',
        Error_PayPassword: '密码必须为纯数字',
        // Error_PayPassword: '',
        // Error_Password: '密码错误',
        Fail_Lic_Info: '图片信息识别失败,请重新上传!',
        Success_Lic_Info: '图片信息识别成功',
        // Fail_People_Info: '营业执照信息识别失败,请重新上传!',
        // Fail_Date_Info: '营业执照信息识别失败,请重新上传!',
        Error_Withdraw: '提现金额无效',
        Error_Position: '获取当前位置失败',
        // Error_Message: '您输入的信息有误',
        // Error_Nimiety: '手机号或密码错误次数过多！请稍后再试或找回密码'
        Error_Number_Password: '手机号或密码错误',
        Phone_Err: '请输入手机号或UID',
        Phone_Input_Err: '手机号输入格式不正确',
        Login_Success: '登陆成功',
        Would_You_Set_Password: '需要设置登陆密码吗？',
        Delete: '删除',
        Set_Your_Password: '请先输入您的密码',
        Not_More_Goods: '没有更多商品了！！！',
        Not_More_Shops: '没有更多店铺了！！！',


        //核对过确定有用到
        Whether_Lengthen: '确认延长收货时间？每笔订单只可延长一次',
        Whether_delete: '确认删除订单删除后不可恢复',
        Error_Address_Length: '详细地址至少字数为3个，最多为100个',
        Error_Password_Confirm: '两次输入密码不一致',
        Error_Address: '地址不完整',
        Error_Open_Time: '请设置开店时间',
        Error_UserName: '请输入正确的卡主姓名',
        Error_ID: '请输入正确的的公民身份证号码',
        Error_Bank: '请输入正确的银行卡号',
        Bank_None: '请选择开户银行',
        Bank_Card_Num: '请输入银行卡号',
        Error_ShopName: '请输入2-30位店铺名称，仅支持中英文及数字。',
        Error_Phone: '请输入正确的手机号码',
        Error_CasPhone: '请输入4-12位数字客服电话',
        Error_Captcha: '验证码错误',
        Code_Error: '请输入验证码',
        Error_Password_Required: '密码不能为空',
        Error_Password_Length: '密码长度应为6~18位',
        Error_Password_Same: '两次密码输入不相同',
        Error_UID: '请输入正确的UID',
        Error_Reason_Required: '请选择退款原因',
        Error_Issue_Length: '问题描述至少为5个字',
        No_UID: '请输入UID',
        No_Uid: 'UID格式不正确',
        No_nextPass: '请再次输入密码',
        No_StoreName: '请输入正确的商店名称',
        No_cate1: '请选择主营行业',
        No_pca: '请选择所属区域',
        No_pickUpSelf: '请选择是否支持自提',
        No_address: '请填写店铺详细地址',
        No_disRange: '请输入折扣范围',
        No_isExp: '请选择商家类型',
        No_disNum: '请输入折扣值',
        No_Principal_Phone: '请输入商家负责人电话',
        No_cshPhone: '请输入客服电话',
        No_linkName: '请输入负责人姓名，且需为2~8位的中文字符',
        No_checkPhone: '您输入的号码有误，请重新输入！',
        No_cardForward: '请上传身份证正面照',
        No_cardBack: '请上传身份证反面照',
        No_cardHand: '请上传手持身份证照片',
        No_Prove: '请上传证明照片',
        No_Prove_type: '请选择证明类型',
        No_Merchant_Prove: '请上传商家证明照',
        No_Booth: '请上传摊位照',
        No_Booth_Environment: '请上传摊位环境照',
        No_Sell_Commodity: '请上传售卖商品照',
        No_validDate: '请输入身份证有效期',
        No_cardHolderName: '请填写卡主姓名',
        No_BankNumber: '请输入银行卡号码',
        No_Bank: '请选择开户银行',
        No_branchBankName: '请选择开户支行',
        No_businessLicense: '请上传营业执照',
        No_shopLic: '请填写统一社会信用代码',
        No_threeInOne: '请选择是否三证合一',
        No_shopLicExp: '请填写营业执照效期',
        No_shopDoorTop: '请上传商家门头照',
        No_shopPhoto: '请上传商家店内照',
        No_reservePhone: '请输入银行预留手机号',
        No_Stocks: '商品库存不足',
        No_Complain: '请添加您的投诉',
        No_GenRe: '请选择提现类别',
        No_Money: '请输入正确的金额',
        No_Withdraw: '请认真阅读《提现提示》',
        failGetBankBranch: '请选择开户银行或开户银行地区',
        No_EvaluateShop: '请对店铺进行评价',
        No_EvaluateLogistics: '请对物流进行评价',
        No_Evaluate: '您还没有输入任何评价',
        No_OpenShopName: '请输入开店人姓名，且需为2~10位的中文字符',


        No_INFO: '请先验证信息'
    },
    Feedback: {
        DOT_TWOM: '上传图片不能超过2M',
        Waiting: '商家正在加急为您处理中',
        // Add_Shopping_Cart_Success: '添加成功，在购物车等着您',
        Empty_Success: '清空成功',
        Failed_Property: '该属性商品暂无库存',
        Unbind_Success: '解绑成功',
        Bind_Success: '绑定成功',
        Sure_Read: '请先勾选开店协议',
        // Feedback_Success: '您的鞭策是我们前进的动力。感谢您的反馈。',
        Set_Success: '设置成功',
        Copy_Success: '复制成功',
        Like_Success: '点赞成功',
        Search_Success: '搜索成功',
        Ver_Success: '验证成功，请进行绑定',
        // Prove_Success: '验证成功',
        upload_failed: '上传失败',
        Rovke_Success: '撤銷成功',
        // Prepare_Time: '商家需要*天*小时准备***（产品名称）',
        // Prepare_Time_Anew_Select: '商家需要*天*小时准备***（产品名称），请重新选择',
        Account_Add_Success: '账号添加成功',
        Account_Delete_Success: '账号删除成功',
        // Save_Success: '保存成功',
        Relieve_Binding: '解除绑定后，银行服务将不能使用。包括但不限于支付、提现等功能',
        // Money_Insufficient_Extract_Defeated: '对不起，您的金额不足，提现失败！',
        // CAM_Insufficient_Balance: '您的CAM余额不足，支付失败！请更换支付方式！',
        // Select_Time_Cancel: '您需在选择的使用时间内到店核销',
        // Already_Reply: '今天已经提醒过了，等待卖家发货',
        // Remind_Success: '提醒成功，等待卖家发货中',
        // Appraise_Success: '评价成功',
        // Remind_Supply: '已提醒商家补货'
        // Have_Source: '已有源头码，无需再绑定'
        // Scan_Defeated_Check: '扫码失败，请核对后重试'
        // Scan_Defeated_Latish: '扫码失败，请稍后重试'
        // Login_Password_Success: '登录密码设置成功,是否现在去设置支付密码'
        // Close_Enter_Leave_Deny: '关闭后您将退出登录，是否留下',
        // Application_Pass_Verify: '您的开店申请已通过，是否前去验证银行卡和签约',
        // Application_Pass_Verify_Signed: '您的开店申请已通过，是否前去签约'

        //核对确定有用到

        Select: '请选择',
        Input: '请输入',
        Deliver_Success: '提醒发货成功',
        wxbind_Success: '绑定成功',
        upload_Success: '上传成功',
        receipt_Success: '延期成功',
        Handle_Success: '操作成功',
        Evaluate_Success: '评论成功',
        Edit_Success: '修改成功',
        EditAdd_Success: '添加成功',
        Send_Success: '发送成功',
        Cancel_Success: '取消成功',
        submit_Success: '提交成功',
        Apply_Success: '提交申请成功',
        Change_Password_Success: '密码修改成功',
        Del_Success: '删除成功',
        Select_Pay: '请选择要结算的商品',
        Select_Consume: '到店消费不能加入购物车',
        Add_Success: '添加成功',
        Address_Err: '暂未获取到您的位置信息',
        Not_Allow_Repeat: '不允许重复添加',
        Collect_Success: '加入收藏夹成功',
        Select_Add: '请选择需要添加的商品',
        Select_Del: '请选择需要删除的物品',
        WeChat_Popup: '根据微信官方要求，微信账户要进行实名认证才能提现到微信零钱（需至少绑定一张银行卡）。CAM收益10元起提，并收6%手续费。其他收入1元起提，免手续费。提现到银行卡，单笔金额不能少于1000元。'

    }
};
